/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wiitbobnjnxwmxfjfcqu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpaXRib2Juam54d214ZmpmY3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NTMxODQsImV4cCI6MjA3NzQyOTE4NH0.apUWzzDOdPiKw_U-jhKSNM-cGOVY1ZGadv_lr8sCwCk"